baseURL = 'http://lucasdesouza.net/'
languageCode = 'en-us'
title = 'Lucas Desouza'
theme = "hugo-resume"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = true

[params]
address = "Dallas, TX"
email = "lucasfds2777@gmail.com"
favicon = "/favicon.ico"
firstName = "Lucas"
lastName = "Desouza"
phone = "1-817-721-9802"
profileImage = "images/picture.jpg"
showEducation = false
showExperience = true
showOpenSource = false
showProjects = true
showPublications = false
showQr = true
showSkills = true