apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: portfolio
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: ghcr.io/lucascarioca/portfolio:latest
          ports:
            - containerPort: 80
              name: portfolio-http
---
kind: Service
metadata:
  namespace: portfolio
  name: portfolio-np-service
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 80
      nodePort: 30000
      targetPort: portfolio-http
  selector:
    app: portfolio
