name: Release new version
on:
  push:
env: 
  VERSION: ${{ github.event.release.tag_name }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - run: echo temp
